export enum PresetEnum{
    ENABLE_ALL = "Enable All",
    DISABLE_ALL = "Disable All",
    SHOPPING = "Shopping",
    INFORMATION = "Information",
    GAMES = "Games",
    BOOKS = "Books",
    IMAGES = "Images",
    VIDEOS = "Videos",
    PODCAST =  "Podcast",
    NEWS = "News",
    //SECOND_HAND = "Second Hand",
    AUDIO = "Audio",
    MOVIES = "Movies",
}